### ISSUE TITLE
address获取

### ISSUE THREAD

**Issue by albertszg** [TuanKay10/Mys_Rob_Goods#1]
大佬，address获取好像出问题了，在浏览器一个网页登陆后，再使用获取地址链接（https://apitakumi.mihoyo.com/account/address/list）也不能得到地址

**Comment by TuanKay10** [comment]
> 大佬，address获取好像出问题了，在浏览器一个网页登陆后，再使用获取地址链接（[https://apitakumi.mihoyo.com/account/address/list）也不能得到地址](https://apitakumi.mihoyo.com/account/address/list%EF%BC%89%E4%B9%9F%E4%B8%8D%E8%83%BD%E5%BE%97%E5%88%B0%E5%ttps://api-takumi.mihoyo.com/account/address/list

> 大佬，address获取好像出问题了，在浏览器一个网页登陆后，再使用获取地址链接（[https://apitakumi.mihoyo.com/account/address/list）也不能得到地址](https://apitakumi.mihoyo.com/account/address/list%EF%BC%89%E4%B9%9F%E4%B8%8D%E8%83%BD%E5%BE%97%E5%88%B0%E5%9C%B0%E5%9D%80)

[https://api-takumi.mihoyo.com/account/address/list](https://api-takumi.mihoyo.com/account/address/list)可以正常获取，没问题呀

**Comment by albertszg** [comment]
{"data":null,"message":"登录失效，请重新登录","retcode":-100}，点开链接是这样的

**Comment by albertszg** [comment]
或者大佬知道就一个地址的话address的ID是多少吗，我直接试试默认ID
😂

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月21日(周日) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TuanKay10/Mys_Goods_Rob] address获取 (Issue #1)




  
大佬，address获取好像出问题了，在浏览器一个网页登陆后，再使用获取地址链接（[https://apitakumi.mihoyo.com/account/address/list）也不能得到地址](https://apitakumi.mihoyo.com/account/address/list%EF%BC%89%E4%B9%9F%E4%B8%8D%E8%83%BD%E5%BE%97%E5%88%B0%E5%ttps://api-takumi.mihoyo.com/account/address/list
   
大佬，address获取好像出问题了，在浏览器一个网页登陆后，再使用获取地址链接（https://apitakumi.mihoyo.com/account/address/list）也不能得到地址
  
https://api-takumi.mihoyo.com/account/address/list可以正常获取，没问题呀
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TuanKay10** [comment]
> {"data":null,"message":"登录失效，请重新登录","retcode":-100}，点开链接是这样的录米游社吧，就是可以看帖子的

> {"data":null,"message":"登录失效，请重新登录","retcode":-100}，点开链接是这样的

字面意思，没有登录，从[米游社](https://bbs.mihoyo.com/ys/)登录吧
